namespace Informedica.MetaVision.Lib




module Constants =

    open Informedica.Utils.Lib.BCL


    let solveGroup = "Oplossen"


    let diluteGroup = "Verdunnen"


    let excludeShapes =
        [|
            "infuus"
            "injectie"
            "injectie/infuus"
        |]


    let solutionMeds =
        [|
            "water", "oplosvloeistof"
            "NaCl 0,9%", "oplosvloeistof"
            "gluc 5%", "oplosvloeistof"
            "gluc 10%", "oplosvloeistof"
            "emulsie", "emulsie"
        |]


    let includeSols =
        [|
            "abatacept"
            "abelcet"
            "acetazolamide"
            "acetylcholine"
            "acetylcysteine"
            "acetylsalicylzuur"
            "aciclovir"
            "adenosine"
            "adrenaline"
            "alanylglutamine"
            "albumine"
            "albutrepenonacog"
            "alcohol"
            "aldesleukine"
            "alemtuzumab"
            "alfacalcidol"
            "alfentanil"
            "alprostadil"
            "alteplase"
            "amfotericine"
            "amikacine"
            "amiodaron"
            "amoxicilline"
            "amoxicilline/clavulaanzuur"
            "anakinra"
            "anidulafungin"
            "anifrolumab"
            "antitrombine"
            "argatroban"
            "arginine"
            "argipressine"
            "artesunaat"
            "ascorbinezuur"
            "astrazeneca"
            "atosiban"
            "atracurium"
            "atropinesulfaat"
            "aztreonam"
            "basiliximab"
            "bcg-medac"
            "belatacept"
            "belimumab"
            "benzylpenicilline"
            "betamethason"
            "bevacizumab"
            "biperideen"
            "bivalirudine"
            "botuline"
            "bumetanide"
            "bupivacaine"
            "c1-esteraseremmer"
            "cabotegravir"
            "calcitonine"
            "calciumgluconaat"
            "cangrelor"
            "caplacizumab"
            "carbacholine"
            "carbetocine"
            "casirivimab"
            "caspofungin"
            "cefazoline"
            "cefiderocol"
            "cefotaxim"
            "ceftazidim"
            "wijzigingen"
            "ceftolozaan-tazobactam"
            "ceftriaxon"
            "cefuroxim"
            "cernevit"
            "cetrorelix"
            "chirhostim"
            "chlooramfenicol"
            "chloorprocaine"
            "choriongonadotrofine"
            "ciclosporine"
            "cidofovir"
            "ciprofloxacine"
            "cisatracurium"
            "citra-lock"
            "clemastine"
            "clindamycine"
            "clonazepam"
            "clonidine"
            "coffeine"
            "colistine"
            "comirnaty"
            "corticoreline"
            "cotrimoxazol"
            "cuvitru"
            "cyanocobalamine"
            "dalteparine"
            "danaparoide"
            "dantroleen"
            "daptomycine"
            "daratumumab"
            "darbepoetine"
            "deferoxamine"
            "defibrotide"
            "denosumab"
            "desmopressine"
            "dexamethason"
            "dexmedetomidine"
            "diazepam"
            "diclofenac"
            "digoxine"
            "dimenhydrinaat"
            "dobutamine"
            "dopamine"
            "doxapram"
            "doxycycline"
            "droperidol"
            "dtp-vaccin"
            "eculizumab"
            "efedrine"
            "efmoroctocog"
            "eftrenonacog"
            "emicizumab"
            "epoetine"
            "epoprostenol"
            "eptacog"
            "ertapenem"
            "erytromycine"
            "esketamine"
            "esmolol"
            "esomeprazol"
            "etanercept"
            "ethanol"
            "etomidaat"
            "factor"
            "fenobarbital"
            "fenol"
            "fentanyl"
            "fentolamine"
            "fenylefrine"
            "fenytoine"
            "ferricarboxymaltose"
            "ferriisomaltoside"
            "ferrioxidesaccharaat"
            "fibrinogeen"
            "filgrastim"
            "flecainide"
            "flucloxacilline"
            "fluconazol"
            "flucytosine"
            "flumazenil"
            "fluoresceine"
            "flupentixol"
            "folinezuur"
            "fondaparinux"
            "fosaprepitant"
            "foscarnet"
            "fosfomycine"
            "furosemide"
            "fytomenadion"
            "ganciclovir"
            "ganirelix"
            "gelatine"
            "gentamicine"
            "glucagon"
            "glucarpidase"
            "glucose"
            "glycerofosforzuur"
            "glycopyrronium"
            "golimumab"
            "gonadoreline"
            "granisetron"
            "haloperidol"
            "hemine"
            "heparine"
            "hepatitis-b-immunoglobuline"
            "hepatitis-b-vaccin"
            "hyaluronidase"
            "hyaluronidase/immunoglobuline"
            "hydrocortison"
            "hydroxocobalamine"
            "hydroxyethylzetmeel"
            "ibuprofen"
            "icatibant"
            "idarucizumab"
            "iloprost"
            "imipenem/cilastatine"
            "immunoglobuline"
            "indocyaninegroen"
            "infliximab"
            "insuline"
            "intralipid"
            "isatuximab"
            "isavuconazol"
            "isoniazide"
            "isoprenaline"
            "covid"
            "kaliumchloride"
            "ketanserine"
            "labetalol"
            "levetiracetam"
            "levobupivacaine"
            "levocarnitine"
            "levofloxacine"
            "levomepromazine"
            "levosimendan"
            "levothyroxine"
            "lidocaine"
            "linezolid"
            "liothyronine"
            "lipidemicrosferen"
            "lorazepam"
            "lutropine"
            "lymfocytenimmunoglobuline"
            "magnesiumchloride"
            "magnesiumsulfaat"
            "mannitol"
            "mecasermine"
            "meningokokkenvaccin"
            "menopauzegonadotrofine"
            "mepivacaine"
            "mepolizumab"
            "mercapto-ethaansulfonzuur"
            "meropenem"
            "metamizol"
            "methadon"
            "methoxypolyethyleenglycol-epoetine"
            "methyleenblauw"
            "methylergometrine"
            "methylnaltrexon"
            "methylprednisolon"
            "metoclopramide"
            "metoprolol"
            "metronidazol"
            "micafungine"
            "midazolam"
            "milrinon"
            "morfine"
            "moxifloxacine"
            "mycofenolaat"
            "nalbufine"
            "naloxon"
            "natalizumab"
            "natrium"
            "natriumbenzoaat"
            "natriumbenzoaat/natriumfenylacetaat"
            "natriumchloride"
            "natriumperchloraat"
            "natriumthiosulfaat"
            "natriumwaterstofcarbonaat"
            "neostigmine"
            "nicardipine"
            "nimodipine"
            "nitroglycerine"
            "nitroprusside"
            "nonacog"
            "noradrenaline"
            "nutriflex"
            "nuvaxovid"
            "octocog"
            "octreotide"
            "olanzapine"
            "olimel"
            "omalizumab"
            "omnipaque"
            "onasemnogene"
            "ondansetron"
            "oxybutynine"
            "oxycodon"
            "oxytocine"
            "palivizumab"
            "pamidronaat"
            "pantoprazol"
            "papaverine"
            "paracetamol"
            "parecoxib"
            "patentblauw"
            "pentamidine"
            "pethidine"
            "piperacilline"
            "piritramide"
            "pneumokokkenvaccin"
            "polidocanol"
            "posaconazol"
            "prednisolon"
            "prilocaine"
            "primene"
            "procainamide"
            "promethazine"
            "propofol"
            "protamine"
            "protrombine"
            "pyridoxine"
            "rabiesvaccin"
            "rasburicase"
            "remdesivir"
            "remifentanil"
            "remimazolam"
            "rhesus(d)"
            "rifampicine"
            "rilpivirine"
            "ringerlactaat"
            "risperidon"
            "rituximab"
            "rocuronium"
            "ropivacaine"
            "ropivacaïne"
            "ropivacaïne/sufentanil"
            "salbutamol"
            "sarilumab"
            "scopolaminebutyl"
            "sildenafil"
            "silibinin"
            "smoflipid"
            "somatoreline"
            "somatropine"
            "sotrovimab"
            "sufentanil"
            "sugammadex"
            "sulfametrol"
            "sulproston"
            "sumatriptan"
            "supliven"
            "suxamethonium"
            "tacrolimus"
            "taurolidine"
            "taurolock"
            "teicoplanine"
            "temoporfine"
            "terlipressine"
            "testosteron"
            "tetanusimmunoglobuline"
            "tetanusvaccin"
            "tetracosactide"
            "theofylline"
            "thiamine"
            "thiopental"
            "thymocytenimmunoglobuline"
            "tigecycline"
            "tirofiban"
            "tobramycine"
            "tocilizumab"
            "tramadol"
            "tranexaminezuur"
            "trastuzumab"
            "triamcinolonacetonide"
            "nieuwe"
            "triamcinolonhexacetonide"
            "triptoreline"
            "trometamol"
            "turoctocog"
            "urokinase"
            "ustekinumab"
            "valproaat"
            "vancomycine"
            "varicellazosterimmunoglobuline"
            "varicella-zostervaccin"
            "vedolizumab"
            "verapamil"
            "verteporfine"
            "vitaminen,"
            "willebrandfactor"
            "vonicog"
            "voriconazol"
            "wilate"
            "zanamivir"
            "zidovudine"
            "zoledroninezuur"
            "zuclopentixol"
        |]


    let routeHeadings =
        [|
            "ExternalCode"
            "RouteName"
            "OrderingType"
            "RouteLocations"
        |]


    let doseFormHeadings =
        [|
            "ExternalCode"
            "DoseFormName"
            "Routes"
            "DefaultUnit"
            "OrderingType"
            "IsDrugInSolution"
            "Category"
            "IsDispensableAmountAllowed"
        |]


    let ingredientHeadings =
        [|
            "ExternalCode"
            "IngredientName"
            "Unit"
        |]


    let medicationHeadings =
        [|
            "ExternalCode"
            "MedicationName"
            "Unit"
            "ATCCode"
            "Status"
            "Format"
            "IncrementValue"
            "CodeSnippetName"
            "Frequencies"
            "DoseForms"
            "Routes"
            "AdditivesGroup"
            "DiluentsGroup"
            "DrugInDiluentGroup"
            "DrugFamily"
            "DrugSubfamily"
            "HideInAllergyEntry"
            "AllergyLookBackTime"
            "AllergyLookBackTimeMeasure"
            "NormalQuantity"
            "NormalQuantityUnit"
            "MaskQuantity"
            "MaskQuantityUnit"
            "NormalRate"
            "NormalRateUnit"
            "MaskRate"
            "MaskRateUnit"
            "NormalConcentration"
            "NormalConcentrationMassUnit"
            "NormalConcentrationVolumeUnit"
            "MaskConcentration"
            "MaskConcentrationMassUnit"
            "MaskConcentrationVolumeUnit"
            "IsFormulary"
        |]


    let complexMedicationHeadings =
        [|
            "ComplexMedicationName"
            "IngredientName"
            "Concentration"
            "ConcentrationUnit"
            "In"
            "InUnit"
        |]


    let brandHeadings =
        [|
            "ExternalCode"
            "BrandName"
            "Manufacturer"
            "MedicationName"
        |]


    let productHeadings =
        [|
            "ExternalCode"
            "ProductID"
            "ProductName"
            "MedicationName"
            "BrandName"
            "Manufacturer"
            "DoseForm"
            "Routes"
            "Status"
            "Format"
            "IncrementValue"
            "Unit"
            "DefaultUnit"
            "IsUnknownStrength"
            "StrengthLEFT"
            "StrengthLEFTUnit"
            "StrengthRIGHT"
            "StrengthRIGHTUnit"
            "DiluentGroup"
            "ProductRequiresReconstitution"
            "IsVolumeKnown"
            "Volume"
            "VolumeUnit"
            "DiluentName"
            "Barcode"
            "ATCCode"
            "MinimumDispensibleAmount"
            "IsFormulary"
        |]


    let orderTemplateHeadings =
        [|
            "OrderTemplateName"
            "MedicationName"
            "ProductName"
            "DoseForm"
            "Route"
            "Location"
            "IsPRN"
            "PRNIndication"
            "MaxDosePer24Hr"
            "MaxDosePer24HrUnit"
            "PatternMode"
            "RepeatEvery"
            "RepeatUnit"
            "PatternPeriod"
            "DosePatternTime"
            "Frequency"
            "FrequencyValue"
            "FrequencyUnit"
            "OrderingStyle"
            "LockerTemplate"
            "TitrationMode"
            "ComponentType"
            "ComponentMedicationName"
            "ComponentProductName"
            "ComponentQuantityVolumeValue"
            "ComponentQuantityVolumeUnit"
            "ComponentConcentrationValue"
            "ComponentConcentrationMassUnit"
            "ComponentConcentrationVolumeUnit"
            "ComponentDrugInDiluentDiluentMedicationName"
            "ComponentDrugInDiluentDiluentProductName"
            "ComponentDrugInDiluentVolumeValue"
            "ComponentDrugInDiluentVolumeUnit"
            "ComponentDailyDosageAmount"
            "ComponentDailyDosageMaxRangeAmount"
            "ComponentDailyDosageUnit / Day"
            "DoseValue"
            "DoseMaxRange"
            "DoseUnit"
            "RateValue"
            "RateMaxRange"
            "RateUnit"
            "TotalVolumeValue"
            "TotalVolumeUnit"
            "InfuseOverValue"
            "InfuseOverMaxRange"
            "InfuseOverUnit"
            "StartMethod"
            "StartMethodValue"
            "StartMethodValueUnit"
            "EndMethod"
            "EndMethodValue"
            "EndMethodValueUnit"
            "DisallowSubstitutionReason"
            "WeightType"
            "Comment"
            "Caption"
            "AvailableInRT"
            "MarkForRemoval"
        |]


    let solutionHeadings =
        [|
            "GPK"
            "Generic"
            "Shape"
            "Route"
            "DoseType"
            "Dep"
            "CVL"
            "PVL"
            "DiluentVol"
            "Diluent"
            "MinAge"
            "MaxAge"
            "MinWeight"
            "MaxWeight"
            "MinDose"
            "MaxDose"
            "Solutions"
            "MinVol"
            "MaxVol"
            "MinPerc"
            "MaxPerc"
            "MinTime"
            "MaxTime"
            "MinRate"
            "MaxRate"
            "RateUnit"
            "Substance"
            "Unit"
            "Quantities"
            "MinQty"
            "MaxQty"
            "MinConc"
            "MaxConc"
        |]


    let parenteral n =
        let alsoEnt =
            match n with
            | _ when n |> String.contains "water" -> true
            | _ when n |> String.contains "gluc"  -> true 
            | _ when n |> String.contains "NaCl"  -> true
            | _ -> false

        [|
            "MedicationName", n
            "Unit", "mL"
            "ATCCode", "parenteraal"
            "Status", "Active"
            "Format", "1,234.5"
            "IncrementValue", "0,1"
            "CodeSnippetName", n
            "Frequencies", "[All]"
            "DoseForms", if alsoEnt then "voeding;parenterale vloeistof" else "parenterale vloeistof"
            "Routes", if alsoEnt then "or;iv" else "iv"
            "AdditivesGroup", "[None]"
            "DiluentsGroup", "[All]"
            "DrugInDiluentGroup", "[None]"
            "DrugFamily", "[None]"
            "DrugSubfamily", "[None]"
            "HideInAllergyEntry", "TRUE"
            "IsFormulary", "TRUE"
        |]


    let enteral n un =
        [|
            "MedicationName", n
            "Unit", un
            "ATCCode", "voeding"
            "Status", "Active"
            "Format", "1,234.5"
            "IncrementValue", "0,1"
            "CodeSnippetName", n
            "Frequencies", "[All]"
            "DoseForms", if un = "g" then "poeder voor voeding" else "voeding"
            "Routes", "or"
            "AdditivesGroup", if un = "g" then "[None]" else "Poeders"
            "DiluentsGroup", if un = "g" then "[None]" else "[All]"
            "DrugInDiluentGroup", "[None]"
            "DrugFamily", "[None]"
            "DrugSubfamily", "[None]"
            "HideInAllergyEntry", "TRUE"
            "IsFormulary", "TRUE"
        |]



